version: "3.7"
services:

  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: ./images/php/Dockerfile
    image: site04
    container_name: site04_php
    working_dir: /var/www/
    volumes:
      - ./www:/var/www
      - ./images/php/:/usr/local/etc/php/conf.d/
    networks:
      - site04
  db:
    image: 'bitnami/postgresql:latest'
    container_name: site04-db
    environment:
      - POSTGRESQL_USERNAME=fl
      - POSTGRESQL_PASSWORD=fl
      - POSTGRESQL_DATABASE=site04
    ports:
      - 5432:5432
    networks:
      - site04
  nginx:
    image: nginx:1.17-alpine
    container_name: site04-nginx
    ports:
      - 80:80
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs:/var/log/nginx
    networks:
      - site04
  cache:
    image: 'bitnami/redis:latest'
    container_name: site04-cache
    environment:
      - REDIS_PASSWORD=fl
    ports:
      - 6379:6379
    networks:
      - site04

networks:
  site04:
    driver: bridge
